### PR TITLE
API v2

### PR DESCRIPTION
**Pull request by dave-maatwebsite**
Closes #1950

### CODE REVIEW

**Review by patrickbrouwers — APPROVED** [review]

**Comment by patrickbrouwers** [comment]
@marcaspers not sure what the merging/releasing strategy for this is

**Comment by marcaspers** [comment]
@patrickbrouwers Because there is no strategy yet ;) 

Moving forward: might it be an idea to have @vicdelfant shortly review this? He is by far the person who used this sdk most, and I want to make sure that current projects wouldn't be affected by this merge.

**Comment by patrickbrouwers** [comment]
@marcaspers yes that would be a good idea

**Comment by vicdelfant** [comment]
The changes look okay in terms of structure and consistency, but I did notice some hardcoded references to the `/v2` prefix in the URL. [Here](https://github.com/juriblox/juriblox-php-sdk/pull/3/files#diff-cd3407a707fc776132b86db2049dc134eac78ae125c260d5f6df0078a5c8ef45R58), for instance:

```php
 $this->driver->patch('v2/collaborations/{collaboration}', [
```

With the client using a relative URL that includes the version prefix, this would result in an URL like `https://api.juriblox.nl/v1/v2/collaborations/...`. Are all endpoints available under `v2`, or only those added by this PR?

**Comment by dave-maatwebsite** [comment]
I removed the hardcoded references to the version and added an option to specify which version to use.

As far as I can see all endpoints are available in v2 and the new collaboration endpoints are only availble in v2.

**Review by vicdelfant — APPROVED** [review]

**Comment by vicdelfant** [comment]
Looks good, thanks!

**Pull request merged**
